In [8]:
from sklearn.datasets import load_boston
import numpy as np
import matplotlib.pyplot as plt
import warnings
from sklearn.model_selection import KFold
from sklearn.preprocessing import PolynomialFeatures


In [9]:
with warnings.catch_warnings():
     warnings.filterwarnings("ignore")
     X, y = load_boston(return_X_y=True)
# scaled X before regression
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)
print(X)
print(std)
X

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[8.59304135e+00 2.32993957e+01 6.85357058e+00 2.53742935e-01
 1.15763115e-01 7.01922514e-01 2.81210326e+01 2.10362836e+00
 8.69865112e+00 1.68370495e+02 2.16280519e+00 9.12046075e+01
 7.13400164e+00]


array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [10]:
X.shape #exploring dataset

(506, 13)

In [11]:
y.shape


(506,)

In [12]:
y=y.reshape(-1,1) #matrix is 1D, need as vector as matrix multiplication is performed using a vector
print("First 5 rows of X:\n", X[:5])  # features
print("\nFirst 5 values of y:\n", y[:5])  # target variable

First 5 rows of X:
 [[6.3200e-03 1.8000e+01 2.3100e+00 0.0000e+00 5.3800e-01 6.5750e+00
  6.5200e+01 4.0900e+00 1.0000e+00 2.9600e+02 1.5300e+01 3.9690e+02
  4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 6.4210e+00
  7.8900e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9690e+02
  9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 7.1850e+00
  6.1100e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9283e+02
  4.0300e+00]
 [3.2370e-02 0.0000e+00 2.1800e+00 0.0000e+00 4.5800e-01 6.9980e+00
  4.5800e+01 6.0622e+00 3.0000e+00 2.2200e+02 1.8700e+01 3.9463e+02
  2.9400e+00]
 [6.9050e-02 0.0000e+00 2.1800e+00 0.0000e+00 4.5800e-01 7.1470e+00
  5.4200e+01 6.0622e+00 3.0000e+00 2.2200e+02 1.8700e+01 3.9690e+02
  5.3300e+00]]

First 5 values of y:
 [[24. ]
 [21.6]
 [34.7]
 [33.4]
 [36.2]]


In [13]:
X = np.c_[np.ones(X.shape[0]), X] #appending 1 to create a y intercept 
print(X[:,0])
print(X[:2,:]) #confirming the appended 1s 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [14]:
#linear regression 
def k_fold_cross_validation(X, y, k=10):
    kf = KFold(n_splits=k, shuffle=True, random_state=42)  
    rerror_train = []  # store training RMSE
    rerror_test = []   # store testing RMSE
    
    for train_index, test_index in kf.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        
        # compute theta using the Normal Equation
        theta = np.linalg.inv(X_train.T @ X_train) @ (X_train.T @ y_train)
        
        # compute predictions and RMSE for training set
        y_train_pred = X_train @ theta
        error_train = y_train - y_train_pred
        rerror_train.append(np.sqrt((error_train.T @ error_train) / len(train_index)))
        
        # compute predictions and RMSE for test set
        y_test_pred = X_test @ theta
        error_test = y_test - y_test_pred
        rerror_test.append(np.sqrt((error_test.T @ error_test) / len(test_index)))
    
    # compute average RMSE
    rmse_train = np.mean(rerror_train)
    rmse_test = np.mean(rerror_test)
    
    print(f"Final Training RMSE: {rmse_train:.4f}")
    print(f"Final Testing RMSE: {rmse_test:.4f}")
    
    return rmse_train, rmse_test

rmse_train, rmse_test = k_fold_cross_validation(X, y, k=10)


Final Training RMSE: 4.6705
Final Testing RMSE: 4.7930


In [15]:
#ridge regression without regularizing bias 

lamda_train = {}
lamda_test = {}
best_lambda = None
best_test_rmse = float('inf')  # initialize to large value to find the min

kf = KFold(n_splits=10, shuffle=True, random_state=42)

# iterate over different lambda values
for lamda in np.logspace(1, 7, num=13):
    rerror_train = []
    rerror_test = []
    
    for train, test in kf.split(X):  # loop over K-Folds
        # identity matrix with bias term excluded from regularization
        identity = np.eye(X.shape[1])
        identity[0, 0] = 0  #no regularization of bias term
        bias_matrix = lamda * identity
        
        theta = np.linalg.inv(X[train].T @ X[train] + bias_matrix) @ (X[train].T @ y[train])
        
        y_train_pred = X[train] @ theta
        error_train = y[train] - y_train_pred
        rerror_train.append(np.sqrt((error_train.T @ error_train) / len(train)))
        
        y_test_pred = X[test] @ theta
        error_test = y[test] - y_test_pred
        rerror_test.append(np.sqrt((error_test.T @ error_test) / len(test)))
    
    # average RMSE for the current lambda
    rmse_train = np.mean(rerror_train)
    rmse_test = np.mean(rerror_test)
    
    # store RMSE values for each lambda
    lamda_train[str(lamda)] = rmse_train
    lamda_test[str(lamda)] = rmse_test
    
    # to get lowest test RMSE
    if rmse_test < best_test_rmse:
        best_test_rmse = rmse_test
        best_lambda = lamda

print("Best Lambda:", best_lambda)
print("Best Test RMSE:", best_test_rmse)
print("\nTraining RMSE values for different lambdas:")
for lamda, rmse in lamda_train.items():
    print(f"Lambda {lamda}: Train RMSE = {rmse}")
    
print("\nTesting RMSE values for different lambdas:")
for lamda, rmse in lamda_test.items():
    print(f"Lambda {lamda}: Test RMSE = {rmse}")


Best Lambda: 10.0
Best Test RMSE: 4.875913122577842

Training RMSE values for different lambdas:
Lambda 10.0: Train RMSE = 4.754308048539244
Lambda 31.622776601683793: Train RMSE = 4.794027383267121
Lambda 100.0: Train RMSE = 4.884360461021243
Lambda 316.22776601683796: Train RMSE = 5.051766689258294
Lambda 1000.0: Train RMSE = 5.2783402593600215
Lambda 3162.2776601683795: Train RMSE = 5.601083631658911
Lambda 10000.0: Train RMSE = 6.113324911024734
Lambda 31622.776601683792: Train RMSE = 6.806000291864548
Lambda 100000.0: Train RMSE = 7.351797840439606
Lambda 316227.7660168379: Train RMSE = 7.65392416502454
Lambda 1000000.0: Train RMSE = 7.8383882522740675
Lambda 3162277.6601683795: Train RMSE = 7.980412523193704
Lambda 10000000.0: Train RMSE = 8.203608836785516

Testing RMSE values for different lambdas:
Lambda 10.0: Test RMSE = 4.875913122577842
Lambda 31.622776601683793: Test RMSE = 4.911421547108196
Lambda 100.0: Test RMSE = 4.997655556616442
Lambda 316.22776601683796: Test RMSE =

In [16]:
#Performance of best regularization parameter

best_lambda = best_lambda  #from previous loop

#variables initalized to track the performance for this best lambda
rerror_train_best = []
rerror_test_best = []

#K-Fold cross-validation rerun with the best lambda
for train, test in kf.split(X):
    identity = np.eye(X.shape[1])
    identity[0, 0] = 0 
    bias_matrix = best_lambda * identity
    
    theta = np.linalg.inv(X[train].T @ X[train] + bias_matrix) @ (X[train].T @ y[train])
    
    y_train_pred = X[train] @ theta
    error_train = y[train] - y_train_pred
    rerror_train_best.append(np.sqrt((error_train.T @ error_train) / len(train)))
    
    y_test_pred = X[test] @ theta
    error_test = y[test] - y_test_pred
    rerror_test_best.append(np.sqrt((error_test.T @ error_test) / len(test)))

avg_rmse_train_best = np.mean(rerror_train_best)
avg_rmse_test_best = np.mean(rerror_test_best)

print(f"\nFor Best Lambda = {best_lambda}:")
print(f"Average Training RMSE: {avg_rmse_train_best}")
print(f"Average Testing RMSE: {avg_rmse_test_best}")


For Best Lambda = 10.0:
Average Training RMSE: 4.754308048539244
Average Testing RMSE: 4.875913122577842


In [20]:
#Polynomial regression 

poly = PolynomialFeatures(degree=2)
X_transformed = poly.fit_transform(X)

rerror_train = []
rerror_test = []

kf = KFold(n_splits=10, shuffle=True, random_state=42)

for train, test in kf.split(X_transformed):
    
    identity = np.eye(X_transformed.shape[1]) 
    identity[0, 0] = 0 
    bias_matrix = best_lambda * identity
    
    theta = np.dot(np.linalg.inv(np.dot(X_transformed[train].T, X_transformed[train]) + bias_matrix), np.dot(X_transformed[train].T, y[train]))
    
    # Training error
    y_hyp = np.dot(X_transformed[train], theta)
    error = y[train] - y_hyp
    rerror_train.append(np.sqrt(np.dot(error.T, error) / len(train)))
    
    # Test error
    y_hyp = np.dot(X_transformed[test], theta)
    error = y[test] - y_hyp
    rerror_test.append(np.sqrt(np.dot(error.T, error) / len(test)))

rmse_train = np.mean(rerror_train)
rmse_test = np.mean(rerror_test)

print("Root mean squared error for train data: ", rmse_train)
print("Root mean squared error for test data: ", rmse_test)



Root mean squared error for train data:  2.5929733674111586
Root mean squared error for test data:  3.6514250736912266


In [23]:
#Multi-variate linear regression using gradient descent

learning_rate = 0.0001
n_iterations = 1000
m=506

rerror_train = []
rerror_test = []

theta = np.random.randn(X.shape[1],1)

kf = KFold(n_splits=10, shuffle=True, random_state=42)

for train,test in kf.split(X):
    for iteration in range(n_iterations):
        gradients = 2/len(train) * (X[train].T.dot(X[train].dot(theta)-y[train]))
        theta = theta - (learning_rate*gradients)
    y_hyp = np.dot(X[train],theta)
    error = np.array(y[train]-y_hyp)
    rerror_train.append(np.sqrt((np.dot(error.T,error))/len(train)))
    y_hyp = np.dot(X[test],theta)
    error = np.array(y[test]-y_hyp)
    rerror_test.append(np.sqrt((np.dot(error.T,error))/len(test)))

rmse_train = np.mean(rerror_train)
rmse_test = np.mean(rerror_test)
print("Root mean squared error for train data: ",rmse_train)
print("Root mean squared error for test data: ",rmse_test)

/tmp/ipykernel_2388240/2230043326.py:20: RuntimeWarning: invalid value encountered in subtract
  theta = theta - (learning_rate*gradients)


Root mean squared error for train data:  nan
Root mean squared error for test data:  nan


In [25]:
#Lasso Regression

learning_rate = 0.001
n_iterations = 1000
alpha = 0.001

kf = KFold(n_splits=10)

rerror_train = []
rerror_test = []

theta = np.random.randn(X.shape[1], 1)  

for train, test in kf.split(X):
    X_train, X_test = X[train], X[test]
    y_train, y_test = y[train], y[test]

    for iteration in range(n_iterations):
        predictions = X_train.dot(theta)
        errors = predictions - y_train
        gradients = np.zeros_like(theta)
        gradients[0] = (2 / len(X_train)) * np.sum(errors)
        gradients[1:] = (2 / len(X_train)) * X_train.T.dot(errors) + alpha * np.sign(theta[1:])
        
        theta = theta - learning_rate * gradients
        
        if np.any(np.isnan(gradients)) or np.any(np.isnan(theta)):
            print(f"NaN or Inf detected in gradients or theta at iteration {iteration}")
            break

    y_train_pred = X_train.dot(theta)
    error_train = y_train - y_train_pred
    rerror_train.append(np.sqrt(np.mean(error_train**2)))

    y_test_pred = X_test.dot(theta)
    error_test = y_test - y_test_pred
    rerror_test.append(np.sqrt(np.mean(error_test**2)))

rmse_train = np.mean(rerror_train)
rmse_test = np.mean(rerror_test)

print(f"Root mean squared error for train data: {rmse_train}")
print(f"Root mean squared error for test data: {rmse_test}")

ValueError: operands could not be broadcast together with shapes (14,1) (13,1) 

In [27]:
#Elastic Net

learning_rate = 0.001
n_iterations = 1000
alpha = 0.001  
r = 0.5 

kf = KFold(n_splits=5)

rerror_train = []
rerror_test = []

theta = np.random.randn(X.shape[1], 1) 

for train, test in kf.split(X):
    X_train, X_test = X[train], X[test]
    y_train, y_test = y[train], y[test]

    for iteration in range(n_iterations):
        predictions = X_train.dot(theta)
        errors = predictions - y_train
        
        gradients = np.zeros_like(theta)
        
        gradients[0] = (2 / len(X_train)) * np.sum(errors)
        
        gradients[1:] = (2 / len(X_train)) * X_train.T.dot(errors) + alpha * (r * np.sign(theta[1:]) + (1 - r) * 2 * theta[1:])
        
        theta = theta - learning_rate * gradients
        
    
    y_train_pred = X_train.dot(theta)
    error_train = y_train - y_train_pred
    rerror_train.append(np.sqrt(np.mean(error_train**2)))

    y_test_pred = X_test.dot(theta)
    error_test = y_test - y_test_pred
    rerror_test.append(np.sqrt(np.mean(error_test**2)))

rmse_train = np.mean(rerror_train)
rmse_test = np.mean(rerror_test)

print(f"Root mean squared error for train data: {rmse_train}")
print(f"Root mean squared error for test data: {rmse_test}")

ValueError: operands could not be broadcast together with shapes (14,1) (13,1) 

Most probably a model that was optimized using gradient descent with the smallest rmse for all the test data amongst all the models would be the best choice. 